// ── Export Service ────────────────────────────────────────────────────
// Generate Word (DOCX) and PDF exports for Minutes of Meeting

const {
  Document: DocxDocument,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
} = require("docx");

const PDFDocument = require("pdfkit");

class ExportService {
  /**
   * Generate a DOCX buffer for a meeting's Minutes of Meeting
   */
  static async generateMomDocx(meeting) {
    const applications = meeting.applications || [];

    const children = [
      // Title
      new Paragraph({
        text: "MINUTES OF MEETING",
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      }),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({ text: meeting.title, bold: true, size: 28 }),
        ],
        spacing: { after: 200 },
      }),

      // Meeting details
      new Paragraph({
        text: "Meeting Details",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Date: ", bold: true }),
          new TextRun(meeting.meeting_date ? new Date(meeting.meeting_date).toLocaleDateString("en-IN") : "—"),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Venue: ", bold: true }),
          new TextRun(meeting.venue || "—"),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Status: ", bold: true }),
          new TextRun(meeting.status?.toUpperCase() || "—"),
        ],
      }),

      // Agenda
      new Paragraph({
        text: "Agenda",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      }),
      new Paragraph({ text: meeting.agenda || "No agenda recorded." }),

      // Applications
      new Paragraph({
        text: "Applications Discussed",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      }),
    ];

    if (applications.length > 0) {
      // Table header
      const headerRow = new TableRow({
        children: ["#", "Reference", "Project Name", "Applicant", "Category", "Decision"].map(
          (text) =>
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text, bold: true, size: 20 })] })],
              width: { size: text === "#" ? 5 : text === "Decision" ? 25 : 15, type: WidthType.PERCENTAGE },
            })
        ),
      });

      const dataRows = applications.map((app, i) => {
        const pivot = app.MeetingApplication || {};
        return new TableRow({
          children: [
            new TableCell({ children: [new Paragraph({ text: String(pivot.agenda_item_number || i + 1) })] }),
            new TableCell({ children: [new Paragraph({ text: app.reference_number || "—" })] }),
            new TableCell({ children: [new Paragraph({ text: app.project_name || "—" })] }),
            new TableCell({ children: [new Paragraph({ text: app.applicant?.name || "—" })] }),
            new TableCell({ children: [new Paragraph({ text: app.category?.code || "—" })] }),
            new TableCell({ children: [new Paragraph({ text: pivot.decision || "Pending" })] }),
          ],
        });
      });

      children.push(
        new Table({
          rows: [headerRow, ...dataRows],
          width: { size: 100, type: WidthType.PERCENTAGE },
        })
      );
    } else {
      children.push(new Paragraph({ text: "No applications discussed." }));
    }

    // Minutes
    children.push(
      new Paragraph({
        text: "Minutes of Meeting",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
      })
    );

    if (meeting.minutes) {
      meeting.minutes.split("\n").forEach((line) => {
        children.push(new Paragraph({ text: line }));
      });
    } else {
      children.push(new Paragraph({ text: "No minutes recorded." }));
    }

    // Footer
    children.push(
      new Paragraph({
        spacing: { before: 600 },
        children: [
          new TextRun({ text: "Generated by PARIVESH 3.0 — CECB Environmental Clearance Portal", italics: true, size: 18 }),
        ],
        alignment: AlignmentType.CENTER,
      })
    );

    const doc = new DocxDocument({
      sections: [{ children }],
    });

    return Packer.toBuffer(doc);
  }

  /**
   * Generate a PDF buffer for a meeting's Minutes of Meeting
   */
  static generateMomPdf(meeting) {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: "A4" });
      const buffers = [];

      doc.on("data", (chunk) => buffers.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(buffers)));
      doc.on("error", reject);

      const applications = meeting.applications || [];

      // Title
      doc.fontSize(20).font("Helvetica-Bold").text("MINUTES OF MEETING", { align: "center" });
      doc.moveDown(0.3);
      doc.fontSize(14).text(meeting.title, { align: "center" });
      doc.moveDown(1);

      // Meeting details
      doc.fontSize(14).font("Helvetica-Bold").text("Meeting Details");
      doc.moveDown(0.3);
      doc.fontSize(11).font("Helvetica");
      doc.text(`Date: ${meeting.meeting_date ? new Date(meeting.meeting_date).toLocaleDateString("en-IN") : "—"}`);
      doc.text(`Venue: ${meeting.venue || "—"}`);
      doc.text(`Status: ${meeting.status?.toUpperCase() || "—"}`);
      doc.moveDown(1);

      // Agenda
      doc.fontSize(14).font("Helvetica-Bold").text("Agenda");
      doc.moveDown(0.3);
      doc.fontSize(11).font("Helvetica").text(meeting.agenda || "No agenda recorded.");
      doc.moveDown(1);

      // Applications
      doc.fontSize(14).font("Helvetica-Bold").text("Applications Discussed");
      doc.moveDown(0.3);

      if (applications.length > 0) {
        applications.forEach((app, i) => {
          const pivot = app.MeetingApplication || {};
          doc.fontSize(11).font("Helvetica-Bold");
          doc.text(`${pivot.agenda_item_number || i + 1}. ${app.reference_number || "—"} — ${app.project_name || "—"}`);
          doc.fontSize(10).font("Helvetica");
          doc.text(`   Applicant: ${app.applicant?.name || "—"} | Category: ${app.category?.code || "—"} | Sector: ${app.sector?.name || "—"}`);
          doc.text(`   Decision: ${pivot.decision || "Pending"}`);
          doc.moveDown(0.5);
        });
      } else {
        doc.fontSize(11).font("Helvetica").text("No applications discussed.");
      }

      doc.moveDown(1);

      // Minutes
      doc.fontSize(14).font("Helvetica-Bold").text("Minutes of Meeting");
      doc.moveDown(0.3);
      doc.fontSize(11).font("Helvetica").text(meeting.minutes || "No minutes recorded.");
      doc.moveDown(2);

      // Footer
      doc.fontSize(9).font("Helvetica-Oblique").text(
        "Generated by PARIVESH 3.0 — CECB Environmental Clearance Portal",
        { align: "center" }
      );

      doc.end();
    });
  }
}

module.exports = ExportService;
