// ── Checklist Data ───────────────────────────────────────────────────
// Static regulatory data derived from official SEIAA/MoEFCC checklists.
// Source: Affidavits.pdf, Checklist - Categories.pdf, EDS Points.pdf
// Mineral types: sand, limestone, bricks, stones, infrastructure, industry, others

// ── Document checklists per mineral/project type ─────────────────────
const DOCUMENT_CHECKLISTS = {
  sand: [
    { sno: 1,  key: "processing_fees",        label: "Processing Fees Details",                                                                 required: true  },
    { sno: 2,  key: "pre_feasibility_report",  label: "Pre-feasibility Report (PFR)",                                                            required: true  },
    { sno: 3,  key: "emp",                     label: "Environmental Management Plan (EMP)",                                                     required: true  },
    { sno: 4,  key: "form_caf",                label: "Form 1 / 1-M / CAF",                                                                     required: true  },
    { sno: 5,  key: "dsr",                     label: "District Survey Report (DSR) / Sand Replenishment Study",                                 required: true  },
    { sno: 6,  key: "sand_replenishment_study", label: "Sand Replenishment Study",                                                             required: true  },
    { sno: 7,  key: "land_documents",          label: "Land Documents (B-1, P-2)",                                                              required: true  },
    { sno: 8,  key: "loi",                     label: "Letter of Intent (LOI)",                                                                  required: true  },
    { sno: 9,  key: "gram_panchayat_noc",      label: "NOC from Gram Panchayat / Local Body",                                                   required: true  },
    { sno: 10, key: "certificate_200m",        label: "200 Meter Certificate",                                                                  required: true  },
    { sno: 11, key: "certificate_500m",        label: "500 Meter Certificate",                                                                  required: true  },
    { sno: 12, key: "marked_delimited",        label: "Marked & Delimited Copy",                                                                required: true  },
    { sno: 13, key: "mining_plan_approval",    label: "Mining Plan Approval Letter",                                                            required: true  },
    { sno: 14, key: "approved_mining_plan",    label: "Approved Mining Plan",                                                                   required: true  },
    { sno: 15, key: "forest_noc",              label: "Forest NOC (Reserved/Protected Forest, National Park, Wildlife Sanctuary, Biodiversity Zone)", required: true  },
    { sno: 16, key: "kml_file",               label: "KML File of Applied Area",                                                               required: true  },
    { sno: 17, key: "cer_details",            label: "CER Details with Consent of Gram Sabha / Concerned Dept.",                               required: true  },
    { sno: 18, key: "all_affidavits",         label: "All Notarized Affidavits",                                                               required: true  },
    { sno: 19, key: "gist_submission",        label: "GIST Submission (Online Form)",                                                          required: true  },
  ],

  limestone: [
    { sno: 1,  key: "processing_fees",        label: "Processing Fees Details",                                                                 required: true  },
    { sno: 2,  key: "pre_feasibility_report",  label: "Pre-feasibility Report (PFR)",                                                            required: true  },
    { sno: 3,  key: "emp",                     label: "Environmental Management Plan (EMP)",                                                     required: true  },
    { sno: 4,  key: "form_caf",                label: "Form 1 / 1-M / CAF",                                                                     required: true  },
    { sno: 5,  key: "dsr",                     label: "District Survey Report (DSR) / Sand Replenishment Study",                                 required: true  },
    { sno: 6,  key: "land_documents",          label: "Land Documents (B-1, P-2)",                                                              required: true  },
    { sno: 7,  key: "landowner_consent",       label: "Consent of the Concerned Landowner(s)",                                                  required: true  },
    { sno: 8,  key: "loi",                     label: "Letter of Intent (LOI)",                                                                  required: true  },
    { sno: 9,  key: "loi_extension_copy",      label: "LoI Extension Copy",                                                                     required: true  },
    { sno: 10,  key: "lease_deed",             label: "Lease Deed",                                                                             required: true  },
    { sno: 11, key: "previous_ec",            label: "Previously Issued EC (Environmental Clearance)",                                         required: true  },
    { sno: 12, key: "ec_compliance_actions",  label: "Actions Taken to Comply with Previously Issued EC",                                      required: true  },
    { sno: 13, key: "past_production_cert",   label: "Past Production Data Certified by Mining Department (Latest)",                           required: true  },
    { sno: 14, key: "gram_panchayat_noc",     label: "NOC from Gram Panchayat / Local Body",                                                   required: true  },
    { sno: 15, key: "certificate_200m",       label: "200 Meter Certificate",                                                                  required: true  },
    { sno: 16, key: "certificate_500m",       label: "500 Meter Certificate",                                                                  required: true  },
    { sno: 17, key: "mining_plan_approval",   label: "Mining Plan Approval Letter",                                                            required: true  },
    { sno: 18, key: "approved_mining_plan",   label: "Approved Mining Plan",                                                                   required: true  },
    { sno: 19, key: "forest_noc",             label: "Forest NOC (Reserved/Protected Forest, National Park, Wildlife Sanctuary, Biodiversity Zone)", required: true  },
    { sno: 20, key: "plantation_completion",  label: "Completion of Tree Plantation as per Previously Issued EC",                              required: true  },
    { sno: 21, key: "water_noc_cgwa",        label: "Water NoC (CGWA)",                                                                       required: true  },
    { sno: 22, key: "cte_cto_cecb",          label: "CTE / CTO from CECB",                                                                   required: true  },
    { sno: 23, key: "geotagged_photos",       label: "Geo-tagged Photographs from All Directions of Project Area",                             required: true  },
    { sno: 24, key: "boundary_strip_report",  label: "7.5 Meter Wide Boundary Strip Status (If Excavated: Restoration Plan)",                  required: true  },
    { sno: 25, key: "drone_video",            label: "Drone Video of Mining Lease Area",                                                       required: true  },
    { sno: 26, key: "kml_file",              label: "KML File of Applied Area",                                                               required: true  },
    { sno: 27, key: "ccr",                   label: "Certified Compliance Report (CCR) — Air & Water Consent (CECB)",                          required: true  },
    { sno: 28, key: "cemp",                  label: "Common Environmental Management Plan (C.E.M.P.)",                                         required: true  },
    { sno: 29, key: "cer_details",           label: "CER Details with Consent of Gram Sabha / Concerned Dept.",                               required: true  },
    { sno: 30, key: "all_affidavits",        label: "All Notarized Affidavits",                                                               required: true  },
    { sno: 31, key: "eia_public_hearing",    label: "EIA Report and Public Hearing (If Applicable)",                                          required: false },
    { sno: 32, key: "gist_submission",       label: "GIST Submission (Online Form)",                                                          required: true  },
  ],

  bricks: [
    { sno: 1,  key: "processing_fees",        label: "Processing Fees Details",                                                                 required: true  },
    { sno: 2,  key: "pre_feasibility_report",  label: "Pre-feasibility Report (PFR)",                                                            required: true  },
    { sno: 3,  key: "emp",                     label: "Environmental Management Plan (EMP)",                                                     required: true  },
    { sno: 4,  key: "form_caf",                label: "Form 1 / 1-M / CAF",                                                                     required: true  },
    { sno: 5,  key: "dsr",                     label: "District Survey Report (DSR)",                                                           required: true  },
    { sno: 6,  key: "land_documents",          label: "Land Documents (B-1, P-2)",                                                              required: true  },
    { sno: 7,  key: "landowner_consent",       label: "Consent of the Concerned Landowner(s)",                                                  required: true  },
    { sno: 8,  key: "loi",                     label: "Letter of Intent (LOI)",                                                                  required: true  },
    { sno: 9,  key: "lease_deed",             label: "Lease Deed",                                                                             required: true  },
    { sno: 10, key: "previous_ec",            label: "Previously Issued EC (Environmental Clearance)",                                         required: true  },
    { sno: 11, key: "ec_compliance_actions",  label: "Actions Taken to Comply with Previously Issued EC",                                      required: true  },
    { sno: 12, key: "past_production_cert",   label: "Past Production Data Certified by Mining Department (Latest)",                           required: true  },
    { sno: 13, key: "gram_panchayat_noc",     label: "NOC from Gram Panchayat / Local Body",                                                   required: true  },
    { sno: 14, key: "panchnama",             label: "Panchnama",                                                                              required: true  },
    { sno: 15, key: "certificate_200m",       label: "200 Meter Certificate",                                                                  required: true  },
    { sno: 16, key: "certificate_500m",       label: "500 Meter Certificate",                                                                  required: true  },
    { sno: 17, key: "mining_plan_approval",   label: "Mining Plan Approval Letter",                                                            required: true  },
    { sno: 18, key: "approved_mining_plan",   label: "Approved Mining Plan",                                                                   required: true  },
    { sno: 19, key: "forest_noc",             label: "Forest NOC (Reserved/Protected Forest, National Park, Wildlife Sanctuary, Biodiversity Zone)", required: true  },
    { sno: 20, key: "plantation_completion",  label: "Completion of Tree Plantation as per Previously Issued EC",                              required: true  },
    { sno: 21, key: "water_noc_cgwa",        label: "Water NoC (CGWA)",                                                                       required: true  },
    { sno: 22, key: "cte_cto_cecb",          label: "CTE / CTO from CECB",                                                                   required: true  },
    { sno: 23, key: "geotagged_photos",       label: "Geo-tagged Photographs from All Directions of Project Area",                             required: true  },
    { sno: 24, key: "boundary_strip_report",  label: "1.0 Meter Wide Boundary Strip Status (If Excavated: Restoration Plan)",                  required: true  },
    { sno: 25, key: "drone_video",            label: "Drone Video of Mining Lease Area",                                                       required: true  },
    { sno: 26, key: "kml_file",              label: "KML File of Applied Area",                                                               required: true  },
    { sno: 27, key: "ccr",                   label: "Certified Compliance Report (CCR) — Air & Water Consent (CECB)",                          required: true  },
    { sno: 28, key: "cemp",                  label: "Common Environmental Management Plan (C.E.M.P.)",                                         required: true  },
    { sno: 29, key: "cer_details",           label: "CER Details with Consent of Gram Sabha / Concerned Dept.",                               required: true  },
    { sno: 30, key: "all_affidavits",        label: "All Notarized Affidavits",                                                               required: true  },
    { sno: 31, key: "eia_public_hearing",    label: "EIA Report and Public Hearing (If Applicable)",                                          required: false },
    { sno: 32, key: "gist_submission",       label: "GIST Submission (Online Form)",                                                          required: true  },
  ],

  infrastructure: [
    { sno: 1,  key: "processing_fees",        label: "Processing Fees Details",                                                                 required: true  },
    { sno: 2,  key: "pre_feasibility_report",  label: "Pre-feasibility Report (PFR)",                                                            required: true  },
    { sno: 3,  key: "emp",                     label: "Environmental Management Plan (EMP)",                                                     required: true  },
    { sno: 4,  key: "form_caf",                label: "Form 1 / 1-M / CAF",                                                                     required: true  },
    { sno: 5,  key: "land_documents",          label: "Land Documents (B-1, P-2)",                                                              required: true  },
    { sno: 6,  key: "previous_ec",            label: "Previously Issued EC (Environmental Clearance)",                                         required: false },
    { sno: 7,  key: "ec_compliance_actions",  label: "Actions Taken to Comply with Previously Issued EC",                                      required: false },
    { sno: 8,  key: "partnership_deed",       label: "Partnership Deed / Consent of Owner(s)",                                                 required: true  },
    { sno: 9,  key: "conceptual_plan",        label: "Conceptual Plan",                                                                        required: true  },
    { sno: 10, key: "approved_layout",        label: "Approved Layout from Town and Country Planning",                                         required: true  },
    { sno: 11, key: "land_use_zoning_map",    label: "Land Use / Zoning Map",                                                                 required: true  },
    { sno: 12, key: "builtup_area_statement", label: "Built-up Area Statement",                                                                required: true  },
    { sno: 13, key: "building_permission",    label: "Building Permission",                                                                    required: true  },
    { sno: 14, key: "water_permission",       label: "Water Permission (NRANVP / CGWA)",                                                       required: true  },
    { sno: 15, key: "stp_design",            label: "STP Design & Reuse Plan / Disinfection Proposal",                                        required: true  },
    { sno: 16, key: "solid_waste_plan",      label: "Solid Waste Management Plan",                                                            required: true  },
    { sno: 17, key: "solar_energy_plan",     label: "Solar Energy Plan",                                                                      required: true  },
    { sno: 18, key: "green_belt_statement",  label: "Green Belt Area Statement",                                                              required: true  },
    { sno: 19, key: "emp_cost_estimates",    label: "EMP Cost Estimates",                                                                     required: true  },
    { sno: 20, key: "nbwl_clearance",        label: "NBWL Clearance (If Project is within 1 km)",                                             required: false },
    { sno: 21, key: "fire_noc",             label: "Fire NOC",                                                                               required: true  },
    { sno: 22, key: "aviation_noc",         label: "Aviation NOC",                                                                           required: false },
    { sno: 23, key: "wildlife_mgmt_plan",   label: "Wildlife Management Plan (If Applicable)",                                                required: false },
    { sno: 24, key: "cte_cto_cecb",         label: "CTE / CTO from CECB",                                                                   required: true  },
    { sno: 25, key: "geotagged_photos",      label: "Geo-tagged Photographs from All Directions of Project Area",                             required: true  },
    { sno: 26, key: "kml_file",             label: "KML File of Applied Area",                                                               required: true  },
    { sno: 27, key: "cer_details",          label: "CER Details with Consent of Gram Sabha / Concerned Dept.",                               required: true  },
    { sno: 28, key: "all_affidavits",       label: "All Notarized Affidavits",                                                               required: true  },
    { sno: 29, key: "eia_public_hearing",   label: "EIA Report and Public Hearing (If Applicable)",                                          required: false },
    { sno: 30, key: "gist_submission",      label: "GIST Submission (Online Form)",                                                          required: true  },
  ],

  industry: [
    { sno: 1,  key: "processing_fees",        label: "Processing Fees Details",                                                                 required: true  },
    { sno: 2,  key: "pre_feasibility_report",  label: "Pre-feasibility Report (PFR)",                                                            required: true  },
    { sno: 3,  key: "emp",                     label: "Environmental Management Plan (EMP)",                                                     required: true  },
    { sno: 4,  key: "form_caf",                label: "Form 1 / 1-M / CAF",                                                                     required: true  },
    { sno: 5,  key: "land_documents",          label: "Land Documents (B-1, P-2)",                                                              required: true  },
    { sno: 6,  key: "landowner_consent",       label: "Consent of the Concerned Landowner(s)",                                                  required: true  },
    { sno: 7,  key: "lease_deed",             label: "Lease Deed",                                                                             required: true  },
    { sno: 8,  key: "previous_ec",            label: "Previously Issued EC (Environmental Clearance)",                                         required: true  },
    { sno: 9,  key: "ec_compliance_actions",  label: "Actions Taken to Comply with Previously Issued EC",                                      required: true  },
    { sno: 10, key: "past_production_cert",   label: "Past Production Data Certified by Mining Department (Latest)",                           required: false },
    { sno: 11, key: "gram_panchayat_noc",     label: "NOC from Gram Panchayat / Local Body",                                                   required: true  },
    { sno: 12, key: "forest_noc",             label: "Forest NOC (Reserved/Protected Forest, National Park, Wildlife Sanctuary, Biodiversity Zone)", required: true  },
    { sno: 13, key: "plantation_completion",  label: "Completion of Tree Plantation as per Previously Issued EC",                              required: true  },
    { sno: 14, key: "land_use_breakup",      label: "Land Use Breakup Details",                                                              required: true  },
    { sno: 15, key: "etp",                   label: "Effluent Treatment Plant (ETP) Details",                                                 required: true  },
    { sno: 16, key: "fire_noc",             label: "Fire NOC",                                                                               required: true  },
    { sno: 17, key: "water_permission",      label: "Water Permission (NRANVP / CGWA)",                                                       required: true  },
    { sno: 18, key: "water_noc_cgwa",        label: "Water NoC (CGWA)",                                                                       required: true  },
    { sno: 19, key: "stp_design",           label: "STP Design & Reuse Plan / Disinfection Proposal",                                        required: true  },
    { sno: 20, key: "emp_cost_estimates",   label: "EMP Cost Estimates",                                                                     required: true  },
    { sno: 21, key: "cte_cto_cecb",         label: "CTE / CTO from CECB",                                                                   required: true  },
    { sno: 22, key: "tor_granted",          label: "ToR (Terms of Reference) Granted",                                                       required: true  },
    { sno: 23, key: "eia_public_hearing",   label: "EIA Report and Public Hearing (If Applicable)",                                          required: false },
    { sno: 24, key: "wildlife_mgmt_plan",   label: "Wildlife Management Plan (If Applicable)",                                                required: false },
    { sno: 25, key: "affidavit_litigation", label: "Affidavit on Pending Litigation",                                                        required: true  },
    { sno: 26, key: "all_affidavits",       label: "All Compliance Affidavits",                                                              required: true  },
    { sno: 27, key: "drone_video",          label: "Drone Video of Project Area",                                                            required: true  },
    { sno: 28, key: "ccr",                 label: "Certified Compliance Report (CCR)",                                                       required: true  },
    { sno: 29, key: "cemp",                label: "Common Environmental Management Plan (C.E.M.P.)",                                         required: true  },
    { sno: 30, key: "cer_details",         label: "CER Details with Consent of Gram Sabha / Concerned Dept.",                               required: true  },
    { sno: 31, key: "gist_submission",     label: "GIST Submission (Online Form)",                                                          required: true  },
  ],

  stones: [
    { sno: 1,  key: "processing_fees",        label: "Processing Fees Details",                                                                 required: true  },
    { sno: 2,  key: "pre_feasibility_report",  label: "Pre-feasibility Report (PFR)",                                                            required: true  },
    { sno: 3,  key: "emp",                     label: "Environmental Management Plan (EMP)",                                                     required: true  },
    { sno: 4,  key: "form_caf",                label: "Form 1 / 1-M / CAF",                                                                     required: true  },
    { sno: 5,  key: "land_documents",          label: "Land Documents (B-1, P-2)",                                                              required: true  },
    { sno: 6,  key: "loi",                     label: "Letter of Intent (LOI)",                                                                  required: true  },
    { sno: 7,  key: "blasting_license_dgms",   label: "Blasting License (DGMS)",                                                               required: true  },
    { sno: 8,  key: "safety_zone_plantation_7_5m", label: "Safety Zone Plantation Details (7.5m Wide)",                                        required: true  },
    { sno: 9,  key: "water_sprinkling_arrangements", label: "Water Sprinkling Arrangements",                                                    required: true  },
    { sno: 10, key: "gram_panchayat_noc",      label: "NOC from Gram Panchayat / Local Body",                                                   required: true  },
    { sno: 11, key: "certificate_200m",        label: "200 Meter Certificate",                                                                  required: true  },
    { sno: 12, key: "certificate_500m",        label: "500 Meter Certificate",                                                                  required: true  },
    { sno: 13, key: "mining_plan_approval",    label: "Mining Plan Approval Letter",                                                            required: true  },
    { sno: 14, key: "approved_mining_plan",    label: "Approved Mining Plan",                                                                   required: true  },
    { sno: 15, key: "forest_noc",              label: "Forest NOC (Reserved/Protected Forest, National Park, Wildlife Sanctuary, Biodiversity Zone)", required: true  },
    { sno: 16, key: "kml_file",               label: "KML File of Applied Area",                                                               required: true  },
    { sno: 17, key: "cer_details",            label: "CER Details with Consent of Gram Sabha / Concerned Dept.",                               required: true  },
    { sno: 18, key: "all_affidavits",         label: "All Notarized Affidavits",                                                               required: true  },
    { sno: 19, key: "gist_submission",        label: "GIST Submission (Online Form)",                                                          required: true  },
  ],

  others: [
    { sno: 1,  key: "processing_fees",        label: "Processing Fees Details",                                                                 required: true  },
    { sno: 2,  key: "pre_feasibility_report",  label: "Pre-feasibility Report (PFR)",                                                            required: true  },
    { sno: 3,  key: "emp",                     label: "Environmental Management Plan (EMP)",                                                     required: true  },
    { sno: 4,  key: "form_caf",                label: "Form 1 / 1-M / CAF",                                                                     required: true  },
    { sno: 5,  key: "land_documents",          label: "Land Documents (B-1, P-2)",                                                              required: true  },
    { sno: 6,  key: "all_affidavits",         label: "All Notarized Affidavits",                                                               required: true  },
    { sno: 7,  key: "gist_submission",        label: "GIST Submission (Online Form)",                                                          required: true  },
  ],
};

// ── Affidavit points per mineral/project type ────────────────────────
const AFFIDAVIT_POINTS = {
  stones: [
    "That top soil will be preserved & stored.",
    "That control blasting will be done by a DGMS authorized license holder.",
    "That completion certificate of 7.5 meter wide safety zone plantation and proposed work under CER activities will be submitted along with Geo-tag photographs in six monthly compliance reports.",
    "That survival rate of Plantation will be 90%.",
    "That demarcation will be done by boundary pillars as Mineral Concession Rules.",
    "That water sprinkling arrangements will be done for fugitive dust emission.",
    "That any type of polluted water will not be released into any natural water source.",
    "That employment will be given to the local people as per the rules of the State Government.",
    "That no court case is pending relating to this project before any Court of Law in India.",
    "That no violation of Notification S.O. 804(E) dated 14/03/2017 issued by the Ministry of Environment, Forest and Climate Change, Government of India.",
    "That the direction given in order by the Honorable Supreme Court on 08/01/2020 writ petition (S) Civil No. 114/2014 common cause vs. Union of India & Ors will be followed.",
    "That the instructions given in the Office Memorandum dated 28/04/2023 issued by the Ministry of Environment, Forest and Climate Change, Government of India, New Delhi will be followed.",
    "That the direction given by the Honourable Supreme Court on order dated 02/08/2017 in common cause vs Union of India writ petition (C) 114 of 2014 will be followed.",
    "That the cutting of trees located in the lease area will be done only after obtaining permission from the authority.",
    "That the conditions given in the environmental clearance will be followed.",
    "That it will be my responsibility to protect all interests related to the owners of the land applied for excavation and to follow all rules of India.",
    "That in future will not carry out any excavation without obtaining environmental clearance and will not carry out any excavation beyond the granted capacity.",
    "That the water meter will be installed as per CGWA norms for the water drawn from the borewell for the mine and its information shall be submitted to the office in the six-monthly compliance report.",
    "That under the Common Environmental Management Plan, the mine owner will bear the amount prescribed in the proposal presented for the mine and will manage and implement provisions in the Common Environmental Management Plan.",
    "That the transportation of minerals will be done as per the SOP/Guidelines issued by CPCB regarding transportation.",
    "That the restoration will be done in the excavated portion of 7.5 meter border strip as per the restoration plan. Saplings will be planted in three rows on the restored area and their names and numbers will be written along with the photograph and the same will be submitted to the office in the six month compliance report.",
    "That no excavation will be done in 7.5 meter safety zone in future.",
    "That amount/expense to be incurred by Project proponent for execution of his part in combined proposal of CER work.",
    "That mining operation does not cause any disturbance to flora & fauna.",
    "That waste material will be used to repair the road and sold with the consent of the Mineral Department.",
    "That proposed CER work will be done as per the proposal presented before the honourable committee.",
    "That proposed plantation will be done within a 7.5 meter lease boundary.",
  ],

  bricks: [
    "That survival rate of Plantation will be 90%.",
    "That water sprinkling arrangements will be done for fugitive dust emission.",
    "That contaminated water will not be discharged into natural water sources.",
    "That demarcation will be done by boundary pillars as Mineral Concession Rules.",
    "That information on the works proposed under CER will be included in the half-yearly report along with geo tagged photographs.",
    "That employment will be given to the local people as per the rules of the State Government.",
    "That no other lease/brick kiln is operated within a radius of 1 kilometer of this applied area.",
    "That no excavation work has been done by me outside this lease area.",
    "That presently bricks are manufactured using clay and fly ash at the rate of 50%-50% mixture.",
    "That the height of the fixed chimney is set at least 35 m.",
    "At present the distance of the fixed chimney installed in the lease area is minimum 800 meters from the populated area.",
    "For firing bricks, zig-zag technology or vertical shaft technology will be used in the brick kiln within a minimum of 2 years period.",
    "That vehicles are kept covered during transportation of raw material/bricks.",
    "That the ash coming out of the brick kiln is again used in the same premises for manufacturing raw bricks.",
    "That the fuel (coal) used in brick manufacturing is purchased from registered coal depot or coal mine.",
    "That approved fuel (coal, agricultural waste, etc.) will be used in brick manufacturing. No hazardous waste like tyres/plastics, paint coke etc. will be used.",
    "That no court case is pending relating to this project before any Court of Law in India.",
    "That no violation of Notification S.O. 804(E) dated 14/03/2017 issued by the Ministry of Environment, Forest and Climate Change, Government of India.",
    "That the direction given by the Honourable Supreme Court on order dated 02/08/2017 in common cause vs Union of India writ petition (C) 114 of 2014 will be followed.",
    "That the instructions given in the Office Memorandum dated 28/04/2023 issued by the Ministry of Environment, Forest and Climate Change, Government of India, New Delhi will be followed.",
    "That the work done under C.E.R. will be maintained for 5 years.",
    "That mitigation measures as given in the Ministry of Environment, Forest and Climate Change OM No. Z-11013/57/2014-IA-II(M) dated 29/10/2014 titled 'Impact of mining activities on settlements' shall be followed.",
    "That prompt approval will be obtained from the Ministry of Environment, Forest and Climate Change/State Ministry if there is any change in the ownership of the mining lease or the lease is transferred. Also ensuring that the application for transfer of environmental clearance is timely as per the provisions of Para 11 of the EIA Notification, 2006, as amended from time to time.",
    "That proposed plantation will be done within a 7.5 meter lease boundary.",
    "That proposed CER work will be done as per the proposal presented before the honourable committee.",
    "That the direction given in order by the Honorable Supreme Court on 08/01/2020 writ petition (S) Civil No. 114/2014 will be followed.",
    "That the cutting of trees located in the lease area will be done only after obtaining permission from the authority.",
    "That the conditions given in the environmental clearance will be followed.",
    "The lease area will be converted to Zig Zag method as per the notification dated 22/02/2022 issued by the Ministry of Environment, Forest and Climate Change.",
    "That fly ash and coal will be kept under the tin shed.",
    "The conditions given in the environmental clearance will be followed and six monthly compliance reports will be submitted to the environment office.",
    "Water sprinkling arrangements for fugitive dust emission.",
    "90% survival rate of Plantation.",
    "Employment given to the local people as per the rules of the State Government.",
    "Any type of polluted water will not be released into any natural water source.",
    "No court case pending relating to this project before any Court of Law in India.",
  ],

  sand: [
    "To comply with the Hon'ble Supreme Court Judgment dated 02/08/2017 in Writ Petition (Civil) No. 114 of 2014 in the matter of Common Cause Vs Union of India.",
    "No violation of Notification S.O. 804(E) dated 14/03/2017 issued by the Ministry of Environment, Forest and Climate Change, Government of India.",
    "Mining shall be done in 60 percent of the total lease area.",
    "The direction given by the Sustainable and Mining guideline 2016 & Enforcement and Monitoring guideline for Sand 2020 will be followed.",
    "The conditions given in the environmental clearance will be followed and six monthly compliance reports will be submitted to the environment office.",
    "Information on the works proposed under CER will be included in the half-yearly report along with geo tagged photographs.",
    "Trees will be planted on both sides of the approached roads.",
    "Minerals will be transported by covering it with tarpaulin sheet.",
    "Vehicles will not be transported through populated areas.",
    "Sand excavation work will not be done during the rainy season.",
    "To comply with the Hon'ble Supreme Court Judgment dated 08/01/2020 in Writ Petition (Civil) No. 114 of 2014 in the matter of Common Cause Vs Union of India.",
    "Sand excavation and filling will be done manually and heavy vehicles will not be allowed to enter the river.",
    "In respect of sand replenishment study, pre-monsoon and post monsoon RL survey reports shall be submitted after excavation before & after mining during the rainy season.",
    "Conditions laid down by the SEIAA, Chhattisgarh will be followed and in case of non-compliance, I will be liable for legal and punitive action.",
    "The conditions given in the environmental clearance will be followed.",
    "Demarcation will be done by boundary pillars as per Mineral Concession Rules.",
    "No excavation work in the area prohibited for excavation i.e. minimum distance from the river bank and 10% of the width of the river.",
    "Assurances given to villagers regarding resolution of various issues during the public hearing will be fulfilled.",
    "Mining will not be done outside the lease area.",
    "The direction given in EC by the Hon'ble Supreme Court of India, Hon'ble High Court, Hon'ble National Green Tribunal (NGT) and any other court will be followed.",
  ],

  others: [
    "Inform MOEF&CC/SEIAA for any change in ownership of the mining lease.",
    "Apply for transfer of Environmental Clearance as per provisions of para 11 of EIA Notification, 2006, as amended from time to time.",
    "That no excavation will be done outside the applied lease area.",
    "To comply with the Hon'ble Supreme Court Judgment dated 08/01/2020 in Writ Petition (Civil) No. 114 of 2014 in the matter of Common Cause Vs Union of India.",
    "That the deficiencies found in the compliance report presented regarding the earlier issued environmental clearance will be rectified in the next 6 months and will be submitted to the office along with the six month compliance report of the environmental clearance to be issued.",
    "To my knowledge, no Schedule 1 species have been found in the vicinity of the mine.",
    "That topsoil extracted from our mine will first be stored within the lease area within the safety zone, up to a height of 1 meter and stored topsoil will not be misused, sold, or used for any other purpose as it will only be used for future refilling within the lease area.",
    "Inspectors/Officers will be allowed to inspect this stored topsoil during their inspections/visits.",
    "That the distance from the applied site to schools, hospitals, and residential area exceeds the standard distances specified in the Chhattisgarh Minor Minerals Act, 2015. Schools rearing report will be submitted.",
  ],

  limestone: [
    "That top soil will be preserved & stored.",
    "That control blasting will be done by a DGMS authorized license holder.",
    "That completion certificate of 7.5 meter wide safety zone plantation and proposed work under CER activities will be submitted along with Geo-tag photographs in six monthly compliance reports.",
    "That survival rate of Plantation will be 90%.",
    "That demarcation will be done by boundary pillars as Mineral Concession Rules.",
    "That water sprinkling arrangements will be done for fugitive dust emission.",
    "That any type of polluted water will not be released into any natural water source.",
    "That employment will be given to the local people as per the rules of the State Government.",
    "That no court case is pending relating to this project before any Court of Law in India.",
    "That no violation of Notification S.O. 804(E) dated 14/03/2017 issued by the Ministry of Environment, Forest and Climate Change, Government of India.",
    "That the conditions given in the environmental clearance will be followed.",
    "That the cutting of trees located in the lease area will be done only after obtaining permission from the authority.",
    "That the transportation of minerals will be done as per the SOP/Guidelines issued by CPCB regarding transportation.",
    "That no excavation will be done in 7.5 meter safety zone in future.",
    "That the restoration will be done in the excavated portion of 7.5 meter border strip as per the restoration plan.",
    "That the water meter will be installed as per CGWA norms for the water drawn from the borewell.",
    "That proposed CER work will be done as per the proposal presented before the honourable committee.",
    "That mining operation does not cause any disturbance to flora & fauna.",
  ],

  infrastructure: [
    "That no violation of Notification S.O. 804(E) dated 14/03/2017 issued by the Ministry of Environment, Forest and Climate Change, Government of India.",
    "That the conditions given in the environmental clearance will be followed.",
    "That no court case is pending relating to this project before any Court of Law in India.",
    "That employment will be given to the local people as per the rules of the State Government.",
    "That any type of polluted water will not be released into any natural water source.",
    "That solid waste will be managed as per the applicable rules and regulations.",
    "That all conditions stipulated by the Hon'ble Supreme Court, High Court, and National Green Tribunal will be complied with.",
  ],

  industry: [
    "That no violation of Notification S.O. 804(E) dated 14/03/2017 issued by the Ministry of Environment, Forest and Climate Change, Government of India.",
    "That the conditions given in the environmental clearance will be followed.",
    "That no court case is pending relating to this project before any Court of Law in India.",
    "That employment will be given to the local people as per the rules of the State Government.",
    "That effluent treatment plant (ETP) will be maintained and operated in accordance with applicable norms.",
    "That no hazardous waste will be disposed of in an unauthorized manner.",
    "That all conditions stipulated by the Hon'ble Supreme Court, High Court, and National Green Tribunal will be complied with.",
    "That there are no pending litigation matters related to this project before any Court of Law in India.",
  ],
};

// ── Standard EDS (Essential Document Sought) Points ─────────────────
// Source: EDS Points.pdf — used by scrutiny team when sending back applications
const EDS_POINTS = [
  "PP shall submit processing fee details.",
  "PP shall submit Pre-feasibility Report (PFR).",
  "PP shall submit Certified Compliance Report of Air and Water Consent issued by CECB.",
  "PP shall submit Letter of Intent (LOI).",
  "PP shall submit LOI Extension copy.",
  "PP shall submit Mining Plan Approval Letter.",
  "PP shall submit Approved Mining Plan.",
  "PP shall submit the details of forest land (if any) and shall submit Stage 1 & Stage 2 clearance.",
  "PP shall submit Land Documents.",
  "PP shall submit Land Documents & Consent of Land Owners (If applicable).",
  "PP shall submit 200 m, 500 m Certificate.",
  "PP shall submit Gram Panchayat NoC.",
  "PP shall submit DSR (Latest) with Sand Replenishment Study.",
  "PP shall submit Sand Replenishment Study.",
  "PP shall submit Marked & Delimited Copy.",
  "PP shall submit revised Forest NOC from DFO, mentioning all khasra no. of applied area & the distance of the lease area from the nearest forest boundary, National Park and Wild Life Sanctuary and Biodiversity Area.",
  "PP shall submit C.E.M.P. details for cluster.",
  "PP shall submit updated EIA Report along with updated ToR compliance.",
  "PP shall submit Wild Life Conservation Plan (Schedule 1 Species as per Notification dated 01/04/2023).",
  "PP shall submit Water NOC for Ground Water Abstraction.",
  "PP shall submit Consent of Land Owners.",
  "PP shall submit notarized affidavit that no Schedule 1 species found.",
  "PP shall submit Schedule 1 Species list as per Notification dated 01/04/2023.",
  "PP shall submit latest Past Production Certificate certified from Mining Department.",
  "PP shall submit CEMP details (If applicable).",
  "PP shall submit Plantation details as per previously issued EC.",
  "PP shall submit Geo-tagged photographs of applied lease area.",
  "PP shall submit Gram Panchayat NoC mentioning Khasra No.",
  "PP shall submit Self Compliance Report of previously issued EC.",
  "PP shall submit Restoration Plan (if excavated).",
  "PP shall submit the updated list of Scheduled species as per Notification dated 01/04/2023 & Wild Life Conservation Plan (If applicable).",
  "PP shall submit Panchnama.",
  "PP shall submit Previously Issued EC (Environmental Clearance).",
  "PP shall submit PFR.",
  "PP shall submit Approved Layout from Town and Country Planning copy.",
  "PP shall submit Land Use / Zoning Map.",
  "PP shall submit Built-up Area Statement.",
  "PP shall submit Building Permission copy.",
  "PP shall submit STP Design & Reuse Plan / Disinfection Proposal.",
  "PP shall submit Solid Waste Management Plan.",
  "PP shall submit Solar Energy Plan.",
  "PP shall submit Green Belt Area Statement.",
  "PP shall submit EMP Cost Estimates.",
  "PP shall submit NBWL Clearance (if project is within 1 km of sanctuary/national park).",
  "PP shall submit Fire NOC.",
  "PP shall submit Aviation NOC (If applicable).",
  "PP shall submit Wildlife Management Plan.",
  "PP shall submit Lease Deed.",
  "PP shall submit 500 m Certificate.",
  "PP shall submit 200 m Certificate (if applicable).",
  "PP shall submit DSR (Latest).",
  "PP shall submit KML file of applied area with properly demarcated boundary.",
  "PP shall submit Drone Video of the applied mining lease area.",
  "PP shall submit CER Details with consent from local authority.",
  "PP shall submit all notarized affidavits points related to project.",
  "PP shall submit the project details (mandatory) via the GIST submission form.",
  "PP shall submit land documents with khasra No. of applied land and consent of land owners (if applicable).",
  "PP shall submit correct and legible copy of land documents containing khasra No. of applied land and consent of land owners (if applicable).",
  "Bring a hardcopy of District Survey Report (DSR - Latest) with Sand Replenishment Study at the time of Presentation.",
  "Bring a hardcopy of District Survey Report (DSR - Latest) at the time of Presentation.",
];

// ── Mineral type labels ──────────────────────────────────────────────
const MINERAL_TYPE_LABELS = {
  sand:           "Sand",
  limestone:      "Limestone",
  bricks:         "Earth Clay / Bricks",
  stones:         "Stones (All Types)",
  infrastructure: "Infrastructure",
  industry:       "Industry",
  others:         "Others",
};

/**
 * Returns the checklist for a given mineral/project type.
 * @param {string} mineralType
 * @returns {Array<{sno, key, label, required}>}
 */
function getChecklist(mineralType) {
  return DOCUMENT_CHECKLISTS[mineralType] || [];
}

/**
 * Resolve a human-readable label for a document key.
 * @param {string} key
 * @returns {string}
 */
function getDocumentLabelByKey(key) {
  if (!key) return "Document";
  for (const list of Object.values(DOCUMENT_CHECKLISTS)) {
    const match = list.find((item) => item.key === key);
    if (match) return match.label;
  }
  return key
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

/**
 * Returns affidavit points for a given mineral/project type.
 * @param {string} mineralType
 * @returns {string[]}
 */
function getAffidavitPoints(mineralType) {
  return AFFIDAVIT_POINTS[mineralType] || [];
}

/**
 * Returns all standard EDS points.
 * @returns {string[]}
 */
function getEdsPoints() {
  return EDS_POINTS;
}

module.exports = {
  DOCUMENT_CHECKLISTS,
  AFFIDAVIT_POINTS,
  EDS_POINTS,
  MINERAL_TYPE_LABELS,
  getChecklist,
  getDocumentLabelByKey,
  getAffidavitPoints,
  getEdsPoints,
};
